### ISSUE TITLE
Max stats after patch update

### ISSUE THREAD

**Issue by bubbabri** [Zarroc2762/E7-Gear-Optimizer#17]
Patch just dropped, but wanted to drop this in about the new stat maximums for items. HP on helmets only go to 2000 max currently. (Trying to input 2360hp on a L70 +15 helmet).

Thanks for all your work!

**Comment by compeanansi** [comment]
Yeah, the cap on flat stats needs to be increased (or removed) in response to the flat stats buff that was just deployed.

**Comment by compeanansi** [comment]
Yeah, the cap on flat stats needs to be increased (or removed) in response to the flat stats buff that was just deployed. @AlexeiA any chance you could get a preview build up with this fixed since @Zarroc2762 is on vacation?

**Comment by AlexeiA** [comment]
Increased maximums of flat stats' values to 9999 for now and updated my preview build (https://github.com/AlexeiA/E7-Gear-Optimizer/releases/)
