### ISSUE TITLE
Unable to import gear as it does not append

### ISSUE THREAD

**Issue by molitar** [Zarroc2762/E7-Gear-Optimizer#3]
There is a serious bug with the OCR exporter and it will not do more then 14 non-enhanced gear at a time.  So I am doing max 14 at a time.. But the importer is not really and importer as it deletes all previous data.
  
This is a bad bug because that means all new gear has to be manually added but you can in a good farming have several dozen new gears to be added. So going to want to use the OCR exporter then import.
 
Please fix import so that it will actually do importing and not overwriting current gear.

**Comment by Zarroc2762** [comment]
It's not a bug. It works as intended. I will add a second button for appending data from a JSON file.

**Comment by Zarroc2762** [comment]
Added in https://github.com/Zarroc2762/E7-Gear-Optimizer/releases/tag/v2.2

**Comment by molitar** [comment]
Awesome thanks!
