### ISSUE TITLE
Cant add DJ basar

### ISSUE THREAD

**Issue by bihero123** [Zarroc2762/E7-Gear-Optimizer#34]
hi, some reasons i cant add DJ Basar, error say, Im a tea cup

**Comment by ellesde** [comment]
I fixed this by deleting the cache folder. This way it forces a download of `db.hero.json` from epicsevendb.com.

![image](https://user-images.githubusercontent.com/30731821/67625438-5b813080-f80c-11e9-9928-6d25af163668.png)

After that I was able to add DJ Basar.
![image](https://user-images.githubusercontent.com/30731821/67625432-4b695100-f80c-11e9-92a1-f0d587fc15e2.png)

**Comment by Zarroc2762** [comment]
You will have to clear the cache after a new hero was added to the game and you have to wait for epicsevendb.com to update their data as this application fetches it's data from there.

You shouldn't have to delete the folder manually. The Clear cache button on the General tab does exactly that.

**Comment by bihero123** [comment]
Hi,
I tried again by clearing cache, it worked. thanks alot for your help
