### ISSUE TITLE
Flat value showing incorrect %

### ISSUE THREAD

**Issue by jdegasperi** [Zarroc2762/E7-Gear-Optimizer#36]
Flat values seem to be transformed into an incorrect % (maybe it's taking into account non awakened stat values?) For example, Ruele's 6/6 level 60 HP is 5474, however, a level 85 +15 neck that gives 2700 HP is shown as giving her a 58% increase instead of aprox 50%. Or a sword giving 425 attack showing 90% increase.
![image](https://user-images.githubusercontent.com/12550280/69257408-c74f8280-0b99-11ea-965f-618639f095cd.png)

**Comment by Zarroc2762** [comment]
Flat stat % values are calculated without awakened stats at the moment. This is on my TODO list, but I'm busy with some personal stuff. I hope I'll be able to do some work on the optimized in december

**Comment by spam8117** [comment]
Hello @Zarroc2762 I successfully used your Optimizer today and it is just insanely good!
Are you still working on this issue (flat value not based on awakened stat)?
Cheers

**Comment by Zarroc2762** [comment]
Hey @spam8117 sry for not answering your question. Somehow I didn't receive a mail after your comment. The issue should be fixed in https://github.com/Zarroc2762/E7-Gear-Optimizer/commit/c4458bf5baf32d5525ab0d3fc96c122ac0fcbe49

**Comment by Zarroc2762** [comment]
fix included in https://github.com/Zarroc2762/E7-Gear-Optimizer/releases/tag/v2.8
