### ISSUE TITLE
kitty Clarissa are not able to add in the optimizer

### ISSUE THREAD

**Issue by Cayde0620** [Zarroc2762/E7-Gear-Optimizer#37]
as title
![image](https://user-images.githubusercontent.com/44105293/71474244-86d8c980-2815-11ea-925d-4e6ab7a6ca0a.png)

**Comment by Zarroc2762** [comment]
should be fixed in https://github.com/Zarroc2762/E7-Gear-Optimizer/commit/c4458bf5baf32d5525ab0d3fc96c122ac0fcbe49

**Comment by Zarroc2762** [comment]
fix included in https://github.com/Zarroc2762/E7-Gear-Optimizer/releases/tag/v2.8
