### ISSUE TITLE
Alencia error

### ISSUE THREAD

**Issue by nghoang1288** [Zarroc2762/E7-Gear-Optimizer#39]
seem getting alencia's info is error. can u help me check it
and i want a feature that i can rearrange my heroes. should u add it in furture?

**Comment by nghoang1288** [comment]
https://imgur.com/a/o0OabMs

**Comment by Zarroc2762** [comment]
Please check Issue https://github.com/Zarroc2762/E7-Gear-Optimizer/issues/40. 
You can sort your heroes by clicking on the column headers of the heroes table.
