### ISSUE TITLE
Error when trying to add Tamarine

### ISSUE THREAD

**Issue by Cayde0620** [Zarroc2762/E7-Gear-Optimizer#4]
Please fix that thank you for your good programme again

**Comment by Zarroc2762** [comment]
This should be fixed in version 2.3 https://github.com/Zarroc2762/E7-Gear-Optimizer/releases/tag/v2.3

Please tell me if it works!

**Comment by Zarroc2762** [comment]
Confirmed fixed by a reddit user with the same problem
