### ISSUE TITLE
All-Rounder Wanda?

### ISSUE THREAD

**Issue by spam8117** [Zarroc2762/E7-Gear-Optimizer#42]
I can't find All-Rounder Wanda, am I doing something wrong or is it not possible to pick her currently?
Thank you!

**Comment by Zarroc2762** [comment]
It's not possible to pick All-Rounder Wanda because epicsevendb.com does not have her data yet. The optimizer fetches all hero data from epicsevendb.com automatically and will be updated when epicsevendb.com is updated.
