### ISSUE TITLE
.NET Framework vs Core (adding Mac/Linux support)

### ISSUE THREAD

**Issue by RaphaelDDL** [Zarroc2762/E7-Gear-Optimizer#49]
Question since I have `-1` knowledge in .NET (other than Razor for asp.net lol):

What is the effort to change from .NET Framework to .NET Core? 

I don't know what are the differences code-wise, I just know that with Core I'll be able to run in Mac [as per this](https://stackoverflow.com/a/31864856/684932). I have OSX Catalina and `wine` doesn't work anymore since Catalina cut 32bit support so can't even try running with it.

I've read about Mono Project which makes Framework run on Mac, but that also requires code changes since isn't full Framework available.

That's it, more a doubt than an issue.

Thanks for the work :)

**Comment by Zarroc2762** [comment]
Hey Raphael, sadly porting to .NET Core won't allow you to run the optimizer on mac because it's a Windows Forms Application. Windows Forms only runs on Windows even if the .NET Core Framework is used. See first paragraph [here](https://docs.microsoft.com/en-us/dotnet/core/porting/winforms).

**Comment by RaphaelDDL** [comment]
Got it, thanks for explaining :)
