### ISSUE TITLE
Multiple Stat Foci?

### ISSUE THREAD

**Issue by compeanansi** [Zarroc2762/E7-Gear-Optimizer#9]
After using this optimizer for a while, the main feature I find myself missing from SWOP is the ability to set multiple possible stats to focus for the neck, ring, boots spots. For example, most supports want either HP% or Def% in neck and ring. Currently, you either have to optimize four times to combine the various possibilities or just leave those slots blank. The same applies for crit chance vs. crit dmg necks. Being able to set (three max?) foci for the optimization would still cut down on possible permutations while leaving open all the relevant possibilities for the build you are pursuing.

**Comment by AlexeiA** [comment]
Such feature is not hard to imlement, but I myself don't use focus at all, as filter can do the job better imho. E.g. instead of setting HP% and Def% for neck and ring, you can just enter desired minimum EHP.

**Comment by compeanansi** [comment]
Yes, no one needs to use foci. Their role is to reduce the number of permutations you need to compute. All they do is reduce the time it takes to get your results. By allowing you to set multiple, you can still reduce the permutations (and thus calc time) while still leaving open all the desired options. This is pretty huge because it can mean the difference between 400m permutations and 80m, just from setting one focus. It's a usability request.

**Comment by AlexeiA** [comment]
Maybe this won't be such an issue in the upcoming version of the Optimizer, as the performance should be significally improved.
Please consider downloading my preview version (https://github.com/AlexeiA/E7-Gear-Optimizer/releases/tag/v2.6.0-preview) and tell your opinion.
Although 400M pemutations is indeed a huge number, so some filtering is a must to speedup the process and avoid memory issues.

**Comment by AlexeiA** [comment]
Implemented multiple stat foci this way:
![2019-08-30_11-26-11](https://user-images.githubusercontent.com/1567057/64010012-9f63fc00-cb21-11e9-8138-d17eb9412ca1.png)

**Comment by compeanansi** [comment]
That looks perfect. I assume it is currently only in your branch? If so, I'll download it to test it.

**Comment by AlexeiA** [comment]
Yes, I released it for testing purposes here: https://github.com/AlexeiA/E7-Gear-Optimizer/releases
